apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: anteater-go 
  janus-idp.io/tekton: anteater-go
  backstage.io/kubernetes-id: anteater-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: anteater-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  